### PR TITLE
Removed unused param 'info' inside handle_existing_user method

### PR DESCRIPTION
**Pull request by pantuza**
This method is used only by the get handler of the class OAuthCallback. The call to the method was updated to remove the 'info' param too.

### CODE REVIEW

**Comment by mlavin** [comment]
This isn't used by the default implementation but it's passed for those who may want to customize the behavior, perhaps updating an existing user's profile info with the most recent data from the third-party site.

**Comment by pantuza** [comment]
Based on what you said, I just realized that the code at get() method was checking if the user is None and deciding to handle existing or not existing user. 

To generalize this behavior, I created the handle_user method. This method verifies if the user exists and 
do the same job as before.  Directly, this method, merges the other two methods (handle_existing_user and handle_new_user) and removes the if statement from get() method and put it inside the handle_user. 

This way, we keep the previous behavior and do not use 'info' as an unused parameter. And, one can 
override the method for doing some expecific and different handling.

**Comment by mlavin** [comment]
What problem does this change solve exactly?

**Comment by pantuza** [comment]
Hi @mlavin, It is not a real problem. It is just a refactoring. 

Instead of checking user inside get() method, I am proposing to make this check inside a user handler function (handle_user). Besides, it removes the necessity of having two methods (handle_existing_user and handle_new_user). 

It is just a class design contribution. There is nothing wrong with the current code execution.

**Comment by mlavin** [comment]
The current design is there to make customization easy similar to how the `FormView` splits the `form_valid` and `form_invalid` cases. I don't see how making this one method makes it easier to extend/override since you would always have to account for both branches.

**Comment by pantuza** [comment]
The form_valid and form_invalid has the same interfaces. Maybe you should try to use 'info' as class attribute, then you does not need to pass it as parameter. It will be available for someone who extends the class without confusing the interface. 

But that is Ok, @mlavin : )

Thank you so much for your time.  And congrats for the project. It is very helpful.

**Comment by mlavin** [comment]
Thank you for your feedback but I don't see this as an improvement. I like the explicitness of passing the `info` parameter rather than tracking that state on the view instance. I think the current pattern in line with the existing CBVs which ship with Django.

**Pull request closed without merging**
